export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT"
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT"
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT"
export const CLEAN_CONSTRUCTOR: "CLEAN_CONSTRUCTOR" = "CLEAN_CONSTRUCTOR"

export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_COMPLETE: "GET_INGREDIENTS_COMPLETE" = "GET_INGREDIENTS_COMPLETE";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";

export const GET_TOKEN: "GET_TOKEN" = "GET_TOKEN";
export const GET_TOKEN_COMPLETE: "GET_TOKEN_COMPLETE" = "GET_TOKEN_COMPLETE";
export const GET_TOKEN_FAILED: "GET_TOKEN_FAILED" = "GET_TOKEN_FAILED";
export const GET_TOKEN_CLEAN_STATE: "GET_TOKEN_CLEAN_STATE" = "GET_TOKEN_CLEAN_STATE"

export const LOGIN_USER: "LOGIN_USER" = "LOGIN_USER";
export const LOGIN_USER_COMPLETE: "LOGIN_USER_COMPLETE" = "LOGIN_USER_COMPLETE";
export const LOGIN_USER_FAILED: "LOGIN_USER_FAILED" = "LOGIN_USER_FAILED";

export const LOG_OUT: "LOG_OUT" = "LOG_OUT";
export const LOG_OUT_COMPLETE: "LOG_OUT_COMPLETE" = "LOG_OUT_COMPLETE";
export const LOG_OUT_FAILED: "LOG_OUT_FAILED" = "LOG_OUT_FAILED";

export const SEND_ORDER: "SEND_ORDER" = "SEND_ORDER";
export const SEND_ORDER_COMPLETE: "SEND_ORDER_COMPLETE" = "SEND_ORDER_COMPLETE";
export const SEND_ORDER_ERROR: "SEND_ORDER_ERROR" = "SEND_ORDER_ERROR";
export const HIDE_ORDER: "HIDE_ORDER" = "HIDE_ORDER"

export const PASSWORD_RESET: "PASSWORD_RESET" = "PASSWORD_RESET";
export const PASSWORD_RESET_COMPLETE: "PASSWORD_RESET_COMPLETE" = "PASSWORD_RESET_COMPLETE";
export const PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED" = "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_CLEAN_STATE: "PASSWORD_RESET_CLEAN_STATE" = "PASSWORD_RESET_CLEAN_STATE";

export const GET_USER_INFO: "GET_USER_INFO" = "GET_USER_INFO";
export const GET_USER_INFO_COMPLETE: "GET_USER_INFO_COMPLETE" = "GET_USER_INFO_COMPLETE";
export const GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED" = "GET_USER_INFO_FAILED";
export const CLEAN_USER_INFO: "CLEAN_USER_INFO" = "CLEAN_USER_INFO";

export const REFRESH_USER_INFO: "REFRESH_USER_INFO" = "REFRESH_USER_INFO";
export const REFRESH_USER_INFO_COMPLETE: "REFRESH_USER_INFO_COMPLETE" = "REFRESH_USER_INFO_COMPLETE";
export const REFRESH_USER_INFO_FAILED: "REFRESH_USER_INFO_FAILED" = "REFRESH_USER_INFO_FAILED";

export const USER_REGISTER: "USER_REGISTER" = "USER_REGISTER";
export const USER_REGISTER_COMPLETE: "USER_REGISTER_COMPLETE" = "USER_REGISTER_COMPLETE";
export const USER_REGISTER_FAILED: "USER_REGISTER_FAILED" = "USER_REGISTER_FAILED";
export const REGISTER_CLEAN_STATE: "REGISTER_CLEAN_STATE" = "REGISTER_CLEAN_STATE";

export const FEED_START: 'FEED_START' = 'FEED_START';
export const FEED_SUCCESS: 'FEED_SUCCESS' = 'FEED_SUCCESS';
export const FEED_ERROR: 'FEED_ERROR' = 'FEED_ERROR';
export const FEED_CLOSED: 'FEED_CLOSED' = 'FEED_CLOSED';
export const FEED_CLOSE: 'FEED_CLOSE' = 'FEED_CLOSE'
export const FEED_GET_MESSAGE: 'FEED_GET_MESSAGE' = 'FEED_GET_MESSAGE';

export const ORDER_HISTORY_START: 'ORDER_HISTORY_START' = 'ORDER_HISTORY_START';
export const ORDER_HISTORY_SUCCESS: 'ORDER_HISTORY_SUCCESS' = 'ORDER_HISTORY_SUCCESS';
export const ORDER_HISTORY_ERROR: 'ORDER_HISTORY_ERROR' = 'ORDER_HISTORY_ERROR';
export const ORDER_HISTORY_CLOSED: 'ORDER_HISTORY_CLOSED' = 'ORDER_HISTORY_CLOSED';
export const ORDER_HISTORY_CLOSE: 'ORDER_HISTORY_CLOSE' = 'ORDER_HISTORY_CLOSE'
export const ORDER_HISTORY_GET_MESSAGE: 'ORDER_HISTORY_GET_MESSAGE' = 'ORDER_HISTORY_GET_MESSAGE';

export const bunUidR2D3 = '928c0cf7-06a9-14e2-fed7-5ae9de559f3c';
export const sauceUid = '513b95b2-21a7-e2cc-dc99-468f496635c3';
export const mainUid = "4180955b-de2e-9b6e-ffa0-d715fab4b5c1";